#!/usr/bin/env bash
# pr.sh — Create PR, run cross-model review, notify human.
# Called after an item (or milestone) passes self-assessment.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="${1:?Usage: pr.sh <repo-dir> <item-number> <item-title> [base-branch]}"
ITEM_NUMBER="${2}"
ITEM_TITLE="${3}"
BASE_BRANCH="${4:-main}"

# ─── Create PR ───────────────────────────────────────────────────────────────
create_pr() {
  cd "$REPO_DIR"

  local branch
  branch=$(git branch --show-current)

  # Push branch
  git push -u origin "$branch" 2>/dev/null || {
    echo "ERROR: Failed to push branch $branch" >&2
    return 1
  }

  # Get diff stats for PR body
  local files_changed lines_added lines_removed
  files_changed=$(git diff --name-only "${BASE_BRANCH}...HEAD" | wc -l | xargs)
  lines_added=$(git diff --stat "${BASE_BRANCH}...HEAD" | tail -1 | grep -o '[0-9]* insertion' | grep -o '[0-9]*' || echo "0")
  lines_removed=$(git diff --stat "${BASE_BRANCH}...HEAD" | tail -1 | grep -o '[0-9]* deletion' | grep -o '[0-9]*' || echo "0")

  # Create PR
  local pr_url
  pr_url=$(gh pr create \
    --title "Item ${ITEM_NUMBER}: ${ITEM_TITLE}" \
    --base "$BASE_BRANCH" \
    --body "$(cat <<EOF
## Summary
Automated PR from workflow automation (Ralph loop).

**Item:** #${ITEM_NUMBER} — ${ITEM_TITLE}
**Files changed:** ${files_changed}
**Lines:** +${lines_added} / -${lines_removed}

## Review Status
- [ ] Claude Code review
- [ ] Codex review
- [ ] CI passing
- [ ] Human approval

---
*Generated by [loopwork](https://github.com/hammadtq/loopwork)*
EOF
)" 2>/dev/null)

  echo "$pr_url"
}

# ─── Run reviews in background ──────────────────────────────────────────────
run_reviews() {
  local review_file
  review_file=$("${SCRIPT_DIR}/review.sh" "$REPO_DIR" "$BASE_BRANCH")
  echo "$review_file"
}

# ─── Notify human (placeholder — Telegram integration comes later) ───────────
notify_human() {
  local pr_url="$1"
  local review_file="$2"

  # For now, just print to terminal
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  PR READY FOR REVIEW"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  Item:   #${ITEM_NUMBER} — ${ITEM_TITLE}"
  echo "  PR:     ${pr_url}"
  echo "  Review: ${review_file}"
  echo "━━━━━━━━━━━━━━━━━��━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""

  # TODO: Slice 5 — Send via Telegram
  # telegram_send "PR ready: ${pr_url}\nItem: #${ITEM_NUMBER} — ${ITEM_TITLE}\nReview: see attached"
}

# ─── Main ────────────────────────────────────────────────────────────────────
main() {
  echo "Creating PR for item ${ITEM_NUMBER}..." >&2

  # Create PR
  local pr_url
  pr_url=$(create_pr)

  if [[ -z "$pr_url" ]]; then
    echo "ERROR: Failed to create PR" >&2
    return 1
  fi

  echo "PR created: $pr_url" >&2

  # Run reviews (non-blocking — the loop will continue to next item)
  local review_file
  review_file=$(run_reviews)

  # Notify
  notify_human "$pr_url" "$review_file"

  # Output PR URL for the loop
  echo "$pr_url"
}

main
