#!/usr/bin/env bash
# pr.sh — Create a PR for a finished item.
#
# Note: this script no longer runs reviews itself. The caller (run.sh) is
# expected to invoke review-fix.sh against the resulting PR so that review
# results actually gate the item's completion and get posted as a PR comment.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="${1:?Usage: pr.sh <repo-dir> <item-number> <item-title> [base-branch]}"
ITEM_NUMBER="${2}"
ITEM_TITLE="${3}"
BASE_BRANCH="${4:-main}"

# ─── Create PR ───────────────────────────────────────────────────────────────
create_pr() {
  cd "$REPO_DIR"

  local branch
  branch=$(git branch --show-current)

  # Push branch
  git push -u origin "$branch" 2>/dev/null || {
    echo "ERROR: Failed to push branch $branch" >&2
    return 1
  }

  # Get diff stats for PR body
  local files_changed lines_added lines_removed
  files_changed=$(git diff --name-only "${BASE_BRANCH}...HEAD" | wc -l | xargs)
  lines_added=$(git diff --stat "${BASE_BRANCH}...HEAD" | tail -1 | grep -o '[0-9]* insertion' | grep -o '[0-9]*' || echo "0")
  lines_removed=$(git diff --stat "${BASE_BRANCH}...HEAD" | tail -1 | grep -o '[0-9]* deletion' | grep -o '[0-9]*' || echo "0")

  local pr_url
  pr_url=$(gh pr create \
    --title "Item ${ITEM_NUMBER}: ${ITEM_TITLE}" \
    --base "$BASE_BRANCH" \
    --body "$(cat <<EOF
## Summary
Automated PR from workflow automation (Ralph loop).

**Item:** #${ITEM_NUMBER} — ${ITEM_TITLE}
**Files changed:** ${files_changed}
**Lines:** +${lines_added} / -${lines_removed}

## Review Status
- [ ] Claude Code review
- [ ] Codex review
- [ ] CI passing
- [ ] Human approval

---
*Generated by [loopwork](https://github.com/hammadtq/loopwork)*
EOF
)" 2>/dev/null)

  echo "$pr_url"
}

main() {
  echo "Creating PR for item ${ITEM_NUMBER}..." >&2

  local pr_url
  pr_url=$(create_pr)

  if [[ -z "$pr_url" ]]; then
    echo "ERROR: Failed to create PR" >&2
    return 1
  fi

  echo "PR created: $pr_url" >&2

  # Output PR URL on stdout (last line) so the caller can parse it.
  echo "$pr_url"
}

main
